- name: Check if Go is installed
  shell:
    cmd: command -v go 2> /dev/null
  ignore_errors: yes
  changed_when: no
  register: go_installation_status

- name: Install Go 1.20
  unarchive:
    src: https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
    dest: /usr/local
    creates: /usr/local/go
    remote_src: yes
  become: yes
  when: go_installation_status.rc | int != 0